project:
  type: website
  output-dir: docs
  
website:
  page-navigation: true
  title: "BEEM - Bayesian methods for ecological and environmental modelling"
  description: "Homepage for BEEM - Bayesian methods for ecological and environmental modelling"
  site-url: "https://peterlevy.github.io/beem-sta210/"

  repo-url: https://github.com/peterlevy/beem-sta210
  repo-actions: [edit, issue]

  open-graph: true

  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2022, Mine Çetinkaya-Rundel"
    background: "#D9E3E4"

  sidebar:
    background: "#D9E3E4"
    logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/peterlevy/beem-sta210
        text: "GitHub organization"
      - icon: code-square
        href: https://www.ceh.ac.uk/training/bayesian-methods-ecological-and-environmental-modelling
        text: "CEH Training"

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: "Course information"
        contents:
          - href: course-overview.qmd
            text: Overview
          - href: course-support.qmd
            text: Support
          - href: course-team.qmd
            text: Teaching team
          - href: index.qmd
            text: Schedule
          - href: course-links.qmd
            text: Useful links
      - section: "Computing"
        contents:
          - href: packages-required.qmd
            text: Installing R packages
          - href: computing-troubleshooting.qmd
            text: Troubleshooting
      - section: "Session materials"
        contents:
          - href: session/session-01.qmd
            text: "Session 1"
          - href: session/session-02.qmd
            text: "Session 2"
          - href: session/session-03.qmd
            text: "Session 3"
          - href: session/session-04.qmd
            text: "Session 4"
          - href: session/session-05.qmd
            text: "Session 5"
          - href: session/session-06.qmd
            text: "Session 6"
          - href: session/session-07.qmd
            text: "Session 7"
          - href: session/session-08.qmd
            text: "Session 8"

format:
  html:
    theme:
      light: [default, ceh3.scss]
      dark: [cosmo, theme-dark.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true

freeze: auto

editor: visual