project:
  type: website
  output-dir: docs
  
website:
  page-navigation: true
  title: "BEEM - Bayesian methods for ecological and environmental modelling"
  description: "Homepage for BEEM - Bayesian methods for ecological and environmental modelling"
  site-url: "https://peterlevy.github.io/beem-sta210/"

  repo-url: https://github.com/peterlevy/beem-sta210
  repo-actions: [edit, issue]

  open-graph: true

  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2022, Mine Çetinkaya-Rundel"
    background: "#D9E3E4"

  sidebar:
    background: "#D9E3E4"
    logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/peterlevy/beem-sta210
        text: "GitHub organization"
      - icon: code-square
        href: https://www.ceh.ac.uk/training/bayesian-methods-ecological-and-environmental-modelling
        text: "CEH Training"

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: "Course information"
        contents:
          - href: course-overview.qmd
            text: Overview
          - href: course-syllabus.qmd
            text: Syllabus
          - href: course-support.qmd
            text: Support
          - href: course-team.qmd
            text: Teaching team
          - href: index.qmd
            text: Schedule
          - href: course-links.qmd
            text: Useful links
          - href: course-faq.qmd
            text: FAQ
      - section: "Computing"
        contents:
          - href: computing-access.qmd
            text: Access
          - href: computing-troubleshooting.qmd
            text: Troubleshooting
      - section: "Session materials"
        contents:
          - href: session/session-1.qmd
            text: "Session 1"
          - href: session/session-2.qmd
            text: "Session 2"
          - href: session/session-3.qmd
            text: "Session 3"
          - href: session/session-4.qmd
            text: "Session 4"
          - href: session/session-5.qmd
            text: "Session 5"
          - href: session/session-6.qmd
            text: "Session 6"
          - href: session/session-7.qmd
            text: "Session 7"
          - href: session/session-8.qmd
            text: "Session 8"
          - href: session/session-9.qmd
            text: "Session 9"
          - href: session/session-10.qmd
            text: "Session 10"
      - section: "Supplemental notes"
        contents:
          - href: supplemental/slr-derivations.qmd
            text: SLR derivations
          - href: supplemental/model-diagnostics-matrix.qmd
            text: Model diagnostics
          - href: supplemental/mlr-matrix.qmd
            text: MLR matrix notation
          - href: supplemental/log-transformations.qmd
            text: Log transformations
          - href: supplemental/model-selection-criteria.qmd
            text: Model selection criteria

format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true

freeze: auto

editor: visual