---
title: "BEEM - Bayesian methods for Ecological and Environmental Modelling"
tbl-colwidths: [5,10,20,10,5,5,5]
---

This page contains an outline of the topics, content, and assignments for the semester. Note that this schedule will be updated as the semester progresses, with all changes documented here.

::: column-screen-inset-right
|         Session         | Day & time       | Topic                            |  Who   |                            Reading                            |                                              Slides                                               |                                                Practical                                                 |
|:-----------------------:|------------------|----------------------------------|:------:|:-------------------------------------------------------------:|:-------------------------------------------------------------------------------------------------:|:--------------------------------------------------------------------------------------------------------:|
| [1](/weeks/week-1.html) | Mon, 1-2 pm      | Welcome & Overview of the course |        |                                                               |                 [🖥️](/slides/lab-0.html "Lab slides"){aria-label="Lab 0 slides"}                  |  [📋](/ae/ae-1-markdown.html "Application exercise"){aria-label="Application Exercise 1 instructions"}   |
|                         | Mon, 2-5 pm      | Bayesian basics                  |   ?    | [📖](/weeks/week-1.html#prepare){aria-label="Week 1 summary"} |              [🖥️](/slides/lec-1.pdf "Lecture slides"){aria-label="Lecture 1 slides"}              |  [📋](/ae/ae-1-markdown.html "Application exercise"){aria-label="Application Exercise 1 instructions"}   |
| [2](/weeks/week-2.html) | Tue, 9.30-11 am  | More Basics                      |   ?    |                                                               |                 [🖥️](/slides/lab-1.html "Lab slides"){aria-label="Lab 1 slides"}                  |                                                                                                          |
|                         |                  | Break                            |        |                                                               |                                                                                                   |                                                                                                          |
|                         | Tue, 11.30- 1 pm | MCMC                             |   DC   | [📖](/weeks/week-2.html#prepare){aria-label="Week 2 summary"} |             [🖥️](/slides/lec-2.html "Lecture slides"){aria-label="Lecture 2 slides"}              |    [📋](/ae/ae-2-mcmc.html "Application exercise"){aria-label="Application Exercise 2 instructions"}     |
|                         |                  | Lunch                            |        |                                                               |                                                                                                   |                                                                                                          |
| [3](/weeks/week-3.html) | Tue, 2-3.30 pm   | Linear modelling                 |   PL   |                                                               |             [🖥️](/slides/lec-3.html "Lecture slides"){aria-label="Lecture 3 slides"}              | [📋](/ae/ae-1-dcbikeshare.html "Application exercise"){aria-label="Application Exercise 1 instructions"} |
|                         |                  | Break                            |        |                                                               |                                                                                                   |                                                                                                          |
|                         | Tue, 4-5 pm      | Linear modelling                 |   PL   |                                                               |             [🖥️](/slides/lec-3.html "Lecture slides"){aria-label="Lecture 3 slides"}              | [📋](/ae/ae-2-dcbikeshare.html "Application exercise"){aria-label="Application Exercise 1 instructions"} |
| [4](/weeks/week-2.html) | Wed, 9.30-11 am  | Model selection & comparison     |  PH?   |                                                               |     [🖥️](/slides/lec-4_model_comparison.pdf "Lecture slides"){aria-label="Lecture 4 slides"}      |                                                                                                          |
|                         |                  | Break                            |        |                                                               |                                                                                                   |                                                                                                          |
|                         | Wed, 11.30- 1 pm | Diagnosing weakness              |   DC   | [📖](/weeks/week-2.html#prepare){aria-label="Week 2 summary"} | [🖥️](/slides/lec-4_diagnosing_model_weakness.pdf "Lecture slides"){aria-label="Lecture 4 slides"} |                                                                                                          |
|                         |                  | Lunch                            |        |                                                               |                                                                                                   |                                                                                                          |
| [5](/weeks/week-3.html) | Wed, 2-3.30 pm   | Hierarchical modelling           |   LB   |                                                               |             [🖥️](/slides/lec-5.html "Lecture slides"){aria-label="Lecture 5 slides"}              | [📋](/ae/ae-1-dcbikeshare.html "Application exercise"){aria-label="Application Exercise 1 instructions"} |
|                         |                  | Break                            |        |                                                               |                                                                                                   |                                                                                                          |
|                         | Wed, 4-5 pm      | Spatial modelling?               |  LB?   |                                                               |          [🖥️](/slides/lec-5-spatial.pdf "Lecture slides"){aria-label="Lecture 5 slides"}          | [📋](/ae/ae-1-dcbikeshare.html "Application exercise"){aria-label="Application Exercise 1 instructions"} |
| [6](/weeks/week-2.html) | Thu, 9.30-11 am  | Measurement and uncertainty      |   PL   |                                                               |             [🖥️](/slides/lec-6.html "Lecture slides"){aria-label="Lecture 6 slides"}              |                                                                                                          |
|                         |                  | Break                            |        |                                                               |                                                                                                   |                                                                                                          |
|                         | Thu, 11.30- 1 pm | Communication of results         | LB/DM? | [📖](/weeks/week-2.html#prepare){aria-label="Week 2 summary"} |       [🖥️](/slides/lec-6_communication.pdf "Lecture slides"){aria-label="Lecture 6 slides"}       |                                                                                                          |
|                         | Thu, 12.30- 1 pm | Software choices                 |   ?    | [📖](/weeks/week-2.html#prepare){aria-label="Week 2 summary"} |             [🖥️](/slides/lec-2.html "Lecture slides"){aria-label="Lecture 2 slides"}              |                                                                                                          |
|                         |                  | Lunch                            |        |                                                               |                                                                                                   |                                                                                                          |
| [7](/weeks/week-3.html) | Thu, 2-3.30 pm   | Process-based modelling          |   DC   |                                                               |             [🖥️](/slides/lec-3.html "Lecture slides"){aria-label="Lecture 3 slides"}              | [📋](/ae/ae-1-dcbikeshare.html "Application exercise"){aria-label="Application Exercise 1 instructions"} |
|                         |                  | Break                            |        |                                                               |                                                                                                   |                                                                                                          |
|                         | Thu, 4-5 pm      | Machine learning                 | DC/PL  |                                                               |             [🖥️](/slides/lec-3.html "Lecture slides"){aria-label="Lecture 3 slides"}              | [📋](/ae/ae-1-dcbikeshare.html "Application exercise"){aria-label="Application Exercise 1 instructions"} |
| [8](/weeks/week-2.html) | Fri, 9.30-11 am  | Group Discussion                 |  all   |                                                               |                 [🖥️](/slides/lab-1.html "Lab slides"){aria-label="Lab 1 slides"}                  |                                                                                                          |
|                         |                  | Break                            |        |                                                               |                                                                                                   |                                                                                                          |
|                         | Fri, 11.30- 1 pm | Group Discussion cont.           |  all   | [📖](/weeks/week-2.html#prepare){aria-label="Week 2 summary"} |             [🖥️](/slides/lec-2.html "Lecture slides"){aria-label="Lecture 2 slides"}              |                                                                                                          |
:::

```{r echo = FALSE}
knitr::knit_exit()
```
